/**
 * BalanceImportPanel — import for previously exported balance data
 * (JSON / CSV / XML, optionally AES-256-GCM encrypted).
 *
 * The drop zone, size check, extension check, file-status card and decrypt
 * flow live in ImportDropPanel. What is specific to balance data is the
 * content sniff below and the parse, which the caller owns.
 */
import { useCallback } from 'react'
import { MAX_IMPORT_MB } from '../constants.js'
import { SCAN_SCHEMAS, readLegacyHeader } from '../utils/scanEnvelope.js'
import ImportDropPanel from './ImportDropPanel.jsx'

const SUPPORTED_EXTS = ['json', 'csv', 'xml']

/**
 * Quick structure sniff — verifies the file was exported by this tool.
 *
 * Heuristic by necessity: these exports carry no tool or version marker, so
 * recognition is by shape. Note the encrypted branch accepts any
 * `{encrypted:true}` JSON, whoever wrote it.
 */
export function sniffBalance(text, ext) {
  if (ext === 'json') {
    try {
      const obj = JSON.parse(text)
      if (obj?.encrypted === true) return true
      const arr = Array.isArray(obj) ? obj : obj?.records
      return Array.isArray(arr) && (obj?._rpcConfig != null || arr[0]?.block != null)
    } catch { return false }
  }
  if (ext === 'csv') return text.trimStart().startsWith('# enjin_balance_export')
  if (ext === 'xml') return text.includes('<enjinBalanceHistory>')
  return false
}

/** True for a JSON payload written by `aesEncrypt`. */
function isEncryptedJson(text, ext) {
  if (ext !== 'json') return false
  try {
    return JSON.parse(text)?.encrypted === true
  } catch { return false }
}

export default function BalanceImportPanel({ onImport, onImportEncrypted, bare = false }) {
  const inspect = useCallback((text, ext) => {
    // A JSON file carrying the shared header identifies itself, so validate
    // that first: it is the only way to refuse a *wrong tool's encrypted* file
    // before asking for a password, since every tool's ciphertext otherwise
    // looks identical. CSV and XML need no such check — their sniffs already
    // match a tool-specific marker.
    if (ext === 'json') {
      let parsed
      try { parsed = JSON.parse(text) } catch { parsed = null }
      try {
        readLegacyHeader(parsed, SCAN_SCHEMAS.BALANCE)
      } catch (e) {
        return { ok: false, reason: e.message }
      }
    }
    if (!sniffBalance(text, ext)) {
      return {
        ok: false,
        reason: "This file doesn't appear to be an export from this tool. "
          + "Only files generated by EnjinSight's Balance Viewer are supported.",
      }
    }
    return { ok: true, encrypted: isEncryptedJson(text, ext) }
  }, [])

  const onFile = useCallback((text, ext, fileName) => onImport(text, ext, fileName), [onImport])

  const onDecrypt = useCallback(
    (text, password, ext, fileName) => onImportEncrypted(text, password, ext, fileName),
    [onImportEncrypted],
  )

  return (
    <ImportDropPanel
      heading={bare ? undefined : 'Load exported balance data'}
      extensions={SUPPORTED_EXTS}
      maxMb={MAX_IMPORT_MB}
      sourceLabel="EnjinSight's Balance Viewer"
      inspect={inspect}
      onFile={onFile}
      onDecrypt={onDecrypt}
      passwordFieldId="balance-dec-pwd"
    />
  )
}
