/**
 * BalanceImportPanel — drag-and-drop / file-picker import for JSON / CSV / XML.
 * Handles encrypted files (.enc.json) by prompting for a decryption password.
 *
 * Security:
 *  - File size validated before reading (MAX_IMPORT_MB)
 *  - Extension validated against allowlist before processing
 *  - Content sniffed against known export signatures before parsing
 *  - All file parsing goes through parseImport() which sanitises field values
 *  - No innerHTML anywhere — all alerts and labels use text content
 */
import { useState, useRef, useCallback } from 'react'
import { Upload, FolderOpen, XCircle, CheckCircle } from 'lucide-react'
import { MAX_IMPORT_MB } from '../constants.js'
import Spinner from './Spinner.jsx'
import Field from './Field.jsx'

const SUPPORTED_EXTS = ['json', 'csv', 'xml']

/** Quick structure sniff — verifies the file was exported by this tool */
function sniffBalance(text, ext) {
  if (ext === 'json') {
    try {
      const obj = JSON.parse(text)
      if (obj?.encrypted === true) return true
      const arr = Array.isArray(obj) ? obj : obj?.records
      return Array.isArray(arr) && (obj?._rpcConfig != null || arr[0]?.block != null)
    } catch { return false }
  }
  if (ext === 'csv') return text.trimStart().startsWith('# enjin_balance_export')
  if (ext === 'xml') return text.includes('<enjinBalanceHistory>')
  return false
}

export default function BalanceImportPanel({ onImport, onImportEncrypted, bare = false }) {
  const [isDragOver, setIsDragOver] = useState(false)
  const [isPending,  setIsPending]  = useState(false)
  const [encPending, setEncPending] = useState(null)  // { text, fname, ext }
  const [decPwd,     setDecPwd]     = useState('')
  const [alert,      setAlert]      = useState(null)  // { type, text } — for post-parse errors
  const [fileStatus, setFileStatus] = useState(null)  // { name, ext?, sizeKb, rejected, reason? }
  const fileInputRef = useRef(null)

  function showAlert(type, text, autoDismiss = true) {
    setAlert({ type, text })
    if (autoDismiss) setTimeout(() => setAlert(null), 7000)
  }

  const processFile = useCallback((file) => {
    setFileStatus(null)
    setAlert(null)
    setEncPending(null)

    const sizeKb = (file.size / 1024).toFixed(1)

    // ── Size check ────────────────────────────────────────────────────────
    if (file.size > MAX_IMPORT_MB * 1024 * 1024) {
      setFileStatus({
        name: file.name, sizeKb, rejected: true,
        reason: `File too large — max ${MAX_IMPORT_MB} MB allowed.`,
      })
      return
    }

    // ── Extension check ───────────────────────────────────────────────────
    const ext = file.name.split('.').pop().toLowerCase()
    if (!SUPPORTED_EXTS.includes(ext)) {
      setFileStatus({
        name: file.name, ext, sizeKb, rejected: true,
        reason: `".${ext}" is not a supported file type. Only .json, .csv, or .xml exports from this tool can be imported.`,
      })
      return
    }

    setIsPending(true)

    const reader = new FileReader()
    reader.onload = ev => {
      const text = ev.target.result

      // ── Content sniff ─────────────────────────────────────────────────
      if (!sniffBalance(text, ext)) {
        setFileStatus({
          name: file.name, ext, sizeKb, rejected: true,
          reason: "This file doesn't appear to be an export from this tool. Only files generated by EnjinSight's Balance Viewer are supported.",
        })
        setIsPending(false)
        return
      }

      setFileStatus({ name: file.name, ext, sizeKb, rejected: false })

      // ── Encrypted JSON ────────────────────────────────────────────────
      if (ext === 'json') {
        try {
          const obj = JSON.parse(text)
          if (obj?.encrypted === true) {
            setEncPending({ text, fname: file.name, ext })
            setIsPending(false)
            return
          }
        } catch { /* fall through to normal import */ }
      }

      onImport(text, ext, file.name)
      setFileStatus(null)
      setIsPending(false)
    }
    reader.onerror = () => {
      setFileStatus({ name: file.name, sizeKb, rejected: true, reason: 'Failed to read the file.' })
      setIsPending(false)
    }
    reader.readAsText(file)
  }, [onImport])

  async function handleDecrypt() {
    if (!encPending) return
    if (!decPwd) { showAlert('err', 'Enter the decryption password.'); return }
    setIsPending(true)
    await onImportEncrypted(encPending.text, decPwd, encPending.ext, encPending.fname)
    setEncPending(null)
    setDecPwd('')
    setIsPending(false)
  }

  // ── Drag and drop ─────────────────────────────────────────────────────────
  function onDragOver(e) { e.preventDefault(); setIsDragOver(true) }
  function onDragLeave() { setIsDragOver(false) }
  function onDrop(e) {
    e.preventDefault()
    setIsDragOver(false)
    const file = e.dataTransfer.files?.[0]
    if (file) processFile(file)
  }
  function onFileChange(e) {
    const file = e.target.files?.[0]
    if (file) processFile(file)
    e.target.value = ''
  }

  return (
    <div className={bare ? '' : 'animate-fade-in data-panel'}>
      {!bare && (
        <div className="mb-3">
          <p className="section-label">Import</p>
          <h3 className="mt-1 font-headline text-base font-bold text-text sm:text-lg">Load exported balance data</h3>
        </div>
      )}

      {/* ── File identification card ──────────────────────────────────────── */}
      {fileStatus && (
        <div className={`mb-3 flex items-start gap-2 rounded-sm border px-3 py-2 text-[11px] leading-snug ${
          fileStatus.rejected
            ? 'border-danger/30 bg-danger/10'
            : 'border-success/30 bg-success/10'
        }`}>
          {fileStatus.rejected
            ? <XCircle size={13} className="text-danger flex-shrink-0 mt-0.5" />
            : <CheckCircle size={13} className="text-success flex-shrink-0 mt-0.5" />}
          <div className="min-w-0 space-y-0.5">
            <div className="flex flex-wrap items-center gap-1.5">
              <span className="max-w-full break-all font-mono text-text/80">{fileStatus.name}</span>
              {fileStatus.ext && (
                <span className={`rounded-sm px-1 py-0.5 text-[9px] font-bold uppercase tracking-widest flex-shrink-0 ${
                  fileStatus.rejected ? 'bg-danger/15 text-danger' : 'bg-success/15 text-success'
                }`}>
                  .{fileStatus.ext}
                </span>
              )}
              <span className="text-muted">{fileStatus.sizeKb} KB</span>
            </div>
            {fileStatus.rejected
              ? <p className="text-danger">{fileStatus.reason}</p>
              : <p className="text-success">File recognized — processing…</p>}
          </div>
        </div>
      )}

      {/* ── Post-parse alert (e.g. decryption errors) ─────────────────────── */}
      {alert && (
        <div role="alert" className={`mb-3 rounded-sm border px-3 py-2 text-xs font-medium ${
          alert.type === 'ok'
            ? 'border-success/30 bg-success/10 text-success'
            : 'border-danger/30 bg-danger/10 text-danger'
        }`}>
          {alert.text}
        </div>
      )}

      {/* ── Drop zone ─────────────────────────────────────────────────────── */}
      <div
        role="button"
        tabIndex={0}
        aria-label="Drop a file or click to browse"
        className={`cursor-pointer rounded-sm border border-dashed p-6 text-center transition-colors sm:p-10 ${
          isDragOver
            ? 'border-cyan bg-cyan/10'
            : 'border-[var(--hairline)] bg-card hover:bg-surface-high'
        }`}
        onClick={() => fileInputRef.current?.click()}
        onKeyDown={e => e.key === 'Enter' && fileInputRef.current?.click()}
        onDragOver={onDragOver}
        onDragLeave={onDragLeave}
        onDrop={onDrop}
      >
        {isPending ? (
          <div className="flex flex-col items-center gap-2">
            <Spinner size={28} />
            <p className="text-sm text-text-secondary">Reading file…</p>
          </div>
        ) : (
          <>
            <FolderOpen size={28} className="mx-auto mb-2 text-text-secondary" />
            <p className="text-sm font-semibold text-text">Drop file here or click to browse</p>
            <p className="mt-1 text-xs text-text-secondary">
              JSON, CSV, XML — max {MAX_IMPORT_MB} MB
            </p>
          </>
        )}
        <input
          ref={fileInputRef}
          type="file"
          accept=".json,.csv,.xml"
          className="hidden"
          onChange={onFileChange}
          aria-hidden
        />
      </div>

      {/* ── Decrypt block ──────────────────────────────────────────────────── */}
      {encPending && (
        <div className="mt-4">
          <div className="mb-3 flex gap-2 rounded-sm border border-cyan/30 bg-cyan/10 px-3 py-2 text-xs text-cyan">
            🔒 This file is AES-256-GCM encrypted. Enter the password to decrypt.
          </div>
          <div className="flex gap-3 items-end">
            <div className="flex-1">
              <Field
                label="Decryption Password"
                id="dec-pwd"
                type="password"
                placeholder="Enter password…"
                maxLength={1024}
                value={decPwd}
                onChange={e => setDecPwd(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && handleDecrypt()}
                controlClassName="font-mono"
              />
            </div>
            <button
              onClick={handleDecrypt}
              disabled={isPending}
              className="btn-primary py-2 px-4 disabled:opacity-40"
            >
              {isPending
                ? <Spinner size={16} tone="on-primary" />
                : <Upload size={14} />}
              Decrypt &amp; Import
            </button>
          </div>
        </div>
      )}
    </div>
  )
}
