/**
 * BalanceImportPanel — drag-and-drop / file-picker import for JSON / CSV / XML.
 * Handles encrypted files (.enc.json) by prompting for a decryption password.
 *
 * Security:
 *  - File size validated before reading (MAX_IMPORT_MB)
 *  - Extension validated against allowlist before processing
 *  - Content sniffed against known export signatures before parsing
 *  - All file parsing goes through parseImport() which sanitises field values
 *  - No innerHTML anywhere — all alerts and labels use text content
 */
import { useState, useRef, useCallback } from 'react'
import { Upload, FolderOpen, XCircle, CheckCircle } from 'lucide-react'
import { MAX_IMPORT_MB } from '../constants.js'

const SUPPORTED_EXTS = ['json', 'csv', 'xml']

/** Quick structure sniff — verifies the file was exported by this tool */
function sniffBalance(text, ext) {
  if (ext === 'json') {
    try {
      const obj = JSON.parse(text)
      if (obj?.encrypted === true) return true
      const arr = Array.isArray(obj) ? obj : obj?.records
      return Array.isArray(arr) && (obj?._rpcConfig != null || arr[0]?.block != null)
    } catch { return false }
  }
  if (ext === 'csv') return text.trimStart().startsWith('# enjin_balance_export')
  if (ext === 'xml') return text.includes('<enjinBalanceHistory>')
  return false
}

export default function BalanceImportPanel({ onImport, onImportEncrypted, bare = false }) {
  const [isDragOver, setIsDragOver] = useState(false)
  const [isPending,  setIsPending]  = useState(false)
  const [encPending, setEncPending] = useState(null)  // { text, fname, ext }
  const [decPwd,     setDecPwd]     = useState('')
  const [alert,      setAlert]      = useState(null)  // { type, text } — for post-parse errors
  const [fileStatus, setFileStatus] = useState(null)  // { name, ext?, sizeKb, rejected, reason? }
  const fileInputRef = useRef(null)

  function showAlert(type, text, autoDismiss = true) {
    setAlert({ type, text })
    if (autoDismiss) setTimeout(() => setAlert(null), 7000)
  }

  const processFile = useCallback((file) => {
    setFileStatus(null)
    setAlert(null)
    setEncPending(null)

    const sizeKb = (file.size / 1024).toFixed(1)

    // ── Size check ────────────────────────────────────────────────────────
    if (file.size > MAX_IMPORT_MB * 1024 * 1024) {
      setFileStatus({
        name: file.name, sizeKb, rejected: true,
        reason: `File too large — max ${MAX_IMPORT_MB} MB allowed.`,
      })
      return
    }

    // ── Extension check ───────────────────────────────────────────────────
    const ext = file.name.split('.').pop().toLowerCase()
    if (!SUPPORTED_EXTS.includes(ext)) {
      setFileStatus({
        name: file.name, ext, sizeKb, rejected: true,
        reason: `".${ext}" is not a supported file type. Only .json, .csv, or .xml exports from this tool can be imported.`,
      })
      return
    }

    setIsPending(true)

    const reader = new FileReader()
    reader.onload = ev => {
      const text = ev.target.result

      // ── Content sniff ─────────────────────────────────────────────────
      if (!sniffBalance(text, ext)) {
        setFileStatus({
          name: file.name, ext, sizeKb, rejected: true,
          reason: "This file doesn't appear to be an export from this tool. Only files generated by EnjinSight's Balance Viewer are supported.",
        })
        setIsPending(false)
        return
      }

      setFileStatus({ name: file.name, ext, sizeKb, rejected: false })

      // ── Encrypted JSON ────────────────────────────────────────────────
      if (ext === 'json') {
        try {
          const obj = JSON.parse(text)
          if (obj?.encrypted === true) {
            setEncPending({ text, fname: file.name, ext })
            setIsPending(false)
            return
          }
        } catch { /* fall through to normal import */ }
      }

      onImport(text, ext, file.name)
      setFileStatus(null)
      setIsPending(false)
    }
    reader.onerror = () => {
      setFileStatus({ name: file.name, sizeKb, rejected: true, reason: 'Failed to read the file.' })
      setIsPending(false)
    }
    reader.readAsText(file)
  }, [onImport])

  async function handleDecrypt() {
    if (!encPending) return
    if (!decPwd) { showAlert('err', 'Enter the decryption password.'); return }
    setIsPending(true)
    await onImportEncrypted(encPending.text, decPwd, encPending.ext, encPending.fname)
    setEncPending(null)
    setDecPwd('')
    setIsPending(false)
  }

  // ── Drag and drop ─────────────────────────────────────────────────────────
  function onDragOver(e) { e.preventDefault(); setIsDragOver(true) }
  function onDragLeave() { setIsDragOver(false) }
  function onDrop(e) {
    e.preventDefault()
    setIsDragOver(false)
    const file = e.dataTransfer.files?.[0]
    if (file) processFile(file)
  }
  function onFileChange(e) {
    const file = e.target.files?.[0]
    if (file) processFile(file)
    e.target.value = ''
  }

  return (
    <div className={bare ? '' : 'animate-fade-in rounded-[1.5rem] bg-surface p-5 shadow-ambient'}>
      {!bare && (
        <div className="mb-4">
          <p className="section-label">Import</p>
          <h3 className="mt-2 font-headline text-2xl font-bold text-text">Load exported balance data</h3>
        </div>
      )}

      {/* ── File identification card ──────────────────────────────────────── */}
      {fileStatus && (
        <div className={`mb-3 flex items-start gap-2.5 p-3 rounded-lg border text-[11px] leading-snug
          ${fileStatus.rejected
            ? 'bg-danger/8 border-danger/25'
            : 'bg-success/8 border-success/25'}`}
        >
          {fileStatus.rejected
            ? <XCircle size={14} className="text-danger flex-shrink-0 mt-0.5" />
            : <CheckCircle size={14} className="text-success flex-shrink-0 mt-0.5" />}
          <div className="min-w-0 space-y-1">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="font-mono text-text/80 truncate max-w-[220px]">{fileStatus.name}</span>
              {fileStatus.ext && (
                <span className={`px-1.5 py-0.5 rounded text-[9px] font-bold uppercase tracking-widest flex-shrink-0
                  ${fileStatus.rejected ? 'bg-danger/15 text-danger' : 'bg-success/15 text-success'}`}>
                  .{fileStatus.ext}
                </span>
              )}
              <span className="text-muted">{fileStatus.sizeKb} KB</span>
            </div>
            {fileStatus.rejected
              ? <p className="text-danger">{fileStatus.reason}</p>
              : <p className="text-success">File recognized — processing…</p>}
          </div>
        </div>
      )}

      {/* ── Post-parse alert (e.g. decryption errors) ─────────────────────── */}
      {alert && (
        <div role="alert" className={`mb-4 px-4 py-2.5 rounded-lg text-sm font-medium
          ${alert.type === 'ok' ? 'bg-success/10 text-success' : 'bg-danger/10 text-danger'}`}>
          {alert.text}
        </div>
      )}

      {/* ── Drop zone ─────────────────────────────────────────────────────── */}
      <div
        role="button"
        tabIndex={0}
        aria-label="Drop a file or click to browse"
        className={`rounded-[1.5rem] p-12 text-center cursor-pointer transition-all
                    ${isDragOver
                      ? 'bg-cyan/10 shadow-cyan-glow'
                      : 'bg-card hover:bg-surface-high'}`}
        style={{ border: '1px dashed rgba(70, 71, 82, 0.18)' }}
        onClick={() => fileInputRef.current?.click()}
        onKeyDown={e => e.key === 'Enter' && fileInputRef.current?.click()}
        onDragOver={onDragOver}
        onDragLeave={onDragLeave}
        onDrop={onDrop}
      >
        {isPending ? (
          <div className="flex flex-col items-center gap-2">
            <span className="w-8 h-8 border-2 border-primary/30 border-t-primary rounded-full animate-spin" />
            <p className="text-sm text-text-secondary">Reading file…</p>
          </div>
        ) : (
          <>
            <FolderOpen size={36} className="mx-auto mb-3 text-text-secondary" />
            <p className="font-semibold text-text mb-1">Drop file here or click to browse</p>
            <p className="text-sm text-text-secondary">
              Supports JSON, CSV, XML exports from this app (max {MAX_IMPORT_MB} MB)
            </p>
          </>
        )}
        <input
          ref={fileInputRef}
          type="file"
          accept=".json,.csv,.xml"
          className="hidden"
          onChange={onFileChange}
          aria-hidden
        />
      </div>

      {/* ── Decrypt block ──────────────────────────────────────────────────── */}
      {encPending && (
        <div className="mt-4">
          <div className="mb-3 flex gap-2 rounded-[1rem] bg-cyan/10 px-4 py-3 text-sm text-cyan">
            🔒 This file is AES-256-GCM encrypted. Enter the password to decrypt.
          </div>
          <div className="flex gap-3 items-end">
            <div className="flex-1">
              <label htmlFor="dec-pwd" className="block text-xs font-bold tracking-widest uppercase text-muted mb-1.5">
                Decryption Password
              </label>
              <input
                id="dec-pwd"
                type="password"
                placeholder="Enter password…"
                maxLength={1024}
                value={decPwd}
                onChange={e => setDecPwd(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && handleDecrypt()}
                className="w-full input-field font-mono"
              />
            </div>
            <button
              onClick={handleDecrypt}
              disabled={isPending}
              className="btn-primary py-2 px-4 disabled:opacity-40"
            >
              {isPending
                ? <span className="w-4 h-4 border-2 border-black/30 border-t-black rounded-full animate-spin" />
                : <Upload size={14} />}
              Decrypt &amp; Import
            </button>
          </div>
        </div>
      )}
    </div>
  )
}
