/**
 * RewardImportPanel — import for previously exported reward history
 * (JSON / CSV / XML, optionally AES-256-GCM encrypted).
 *
 * Lifted out of RewardHistoryViewer.jsx, which had it inline in a ~1970-line
 * file alongside its own copy of the drop zone, size check and decrypt block.
 * Those now live in ImportDropPanel; what remains here is the content sniff
 * and the parse.
 */
import { useCallback } from 'react'
import { MAX_IMPORT_MB } from '../constants.js'
import { aesDecrypt } from '../utils/balanceExport.js'
import { SCAN_SCHEMAS, readLegacyHeader } from '../utils/scanEnvelope.js'
import ImportDropPanel from './ImportDropPanel.jsx'

const SUPPORTED_EXTS = ['json', 'csv', 'xml']

/**
 * Quick structure sniff — verifies the file was exported by this tool.
 *
 * Heuristic by necessity: these exports carry no tool or version marker, so
 * recognition is by shape. Note the encrypted branch accepts any
 * `{encrypted:true}` JSON, whoever wrote it.
 */
export function sniffReward(text, ext) {
  if (ext === 'json') {
    try {
      const obj = JSON.parse(text)
      if (obj?.encrypted === true) return true
      const arr = Array.isArray(obj) ? obj : obj?.records
      return Array.isArray(arr) && (obj?._meta != null || arr[0]?.era != null)
    } catch { return false }
  }
  if (ext === 'csv') {
    const firstLine = text.trimStart().split(/\r?\n/).find(l => !l.startsWith('#')) ?? ''
    return firstLine.includes('era') && firstLine.includes('pool_id')
  }
  if (ext === 'xml') return text.includes('<enjinRewardHistory>')
  return false
}

/** True for a JSON payload written by `aesEncrypt`. */
function isEncryptedJson(text, ext) {
  if (ext !== 'json') return false
  try {
    return JSON.parse(text)?.encrypted === true
  } catch { return false }
}

/**
 * @param {object} props
 * @param {(text: string, ext: string) => {results: object[], meta: object|null}} props.parse
 *   `parseRewardImport`, injected so this component does not import back into
 *   its former host.
 * @param {(results: object[], meta: object|null, header: object|null, fileName: string) => void} props.onImport
 */
export default function RewardImportPanel({ parse, onImport }) {
  const inspect = useCallback((text, ext) => {
    // A JSON file carrying the shared header identifies itself, so validate
    // that first: it is the only way to refuse a *wrong tool's encrypted* file
    // before asking for a password, since every tool's ciphertext otherwise
    // looks identical. CSV and XML need no such check — their sniffs already
    // match a tool-specific marker.
    if (ext === 'json') {
      let parsed
      try { parsed = JSON.parse(text) } catch { parsed = null }
      try {
        readLegacyHeader(parsed, SCAN_SCHEMAS.REWARD)
      } catch (e) {
        return { ok: false, reason: e.message }
      }
    }
    if (!sniffReward(text, ext)) {
      return {
        ok: false,
        reason: "This file doesn't appear to be an export from this tool. "
          + "Only files generated by EnjinSight's Reward History Viewer are supported.",
      }
    }
    return { ok: true, encrypted: isEncryptedJson(text, ext) }
  }, [])

  // parse throws on a malformed file — ImportDropPanel shows the message,
  // including the row number for a bad CSV row. `header` is null for an export
  // predating the shared header; the caller's banner degrades accordingly.
  const onFile = useCallback((text, ext, fileName) => {
    const { results, meta, header } = parse(text, ext)
    onImport(results, meta, header, fileName)
  }, [parse, onImport])

  const onDecrypt = useCallback(async (text, password, ext, fileName) => {
    const plain = await aesDecrypt(text, password)
    const { results, meta, header } = parse(plain, 'json')
    onImport(results, meta, header, fileName)
  }, [parse, onImport])

  return (
    <ImportDropPanel
      extensions={SUPPORTED_EXTS}
      maxMb={MAX_IMPORT_MB}
      sourceLabel="EnjinSight's Reward History Viewer"
      inspect={inspect}
      onFile={onFile}
      onDecrypt={onDecrypt}
      passwordFieldId="reward-dec-pwd"
    />
  )
}
